server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:com/edu/huatec/mobileshop/mapper/*.xml
  type-aliases-package: com.edu.huatec.mobileshop.entity

#showSql
logging:
  level:
    com:
      edu:
        huatec:
         mobileshop:
           mapper: debug
